[package]
name = "powerset-enum-attr"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/rust-powerset-enum"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.34"
quote = "0.6.12"
