[package]
name = "powerset-enum-examples"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/rust-powerset-enum"

[dependencies]
powerset-enum = { path = "../powerset-enum" }
